name       : system-config-printer
version    : 1.5.18
release    : 28
source     :
    - https://github.com/OpenPrinting/system-config-printer/releases/download/v1.5.18/system-config-printer-1.5.18.tar.xz : b1a69e1b4ec2add569a87aeca811a37c5361ee6ae327ec852b79e64223e34bee
license    : GPL-2.0-only
component  : desktop.core
summary    : Graphical user interface for CUPS administration
description: |
    Graphical user interface for CUPS administration
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
    - autoconf-archive
    - cups-devel
    - cups-pk-helper
    - desktop-file-utils
    - docbook-xml
    - intltool
    - pycups
    - xmlto
rundeps    :
    - cups-filters
    - cups-pk-helper
    - foomatic-db-engine
    - ghostscript
    - gutenprint
    - nss-mdns
    - pycups
    - python3-dbus
    - python-gobject
    - python-pycurl
    - python-pysmbc
    - python-requests
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-man-page-doctype.patch
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0001-dbus-Fix-broken-bindir.patch
    touch ChangeLog README INSTALL
    ./bootstrap
    %configure $ex_opts --with-cups-serverbin-dir=/usr/lib/cups
build      : |
    %make
    %python3_setup
install    : |
    %make_install

    # Manually sort out python module due to ancient distutils
    rm -fr $installdir/usr/lib/python%python3_version%/site-packages/cupshelpers-1.0-py%python3_version%.egg
    %python3_install
