name       : system-config-printer
version    : 1.5.7
release    : 5
source     :
    - http://cyberelk.net/tim/data/system-config-printer/1.5/system-config-printer-1.5.7.tar.xz : f6b57bbb356b40006e48c059fe5625d8c0ff4217fa10b9675c161527c4fcacef
license    : GPL-2.0
component  : desktop.core
summary    : Graphical user interface for CUPS administration
description: |
    Graphical user interface for CUPS administration
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(python-3.5)
    - desktop-file-utils
    - docbook-xml
    - pycups
    - xmlto
rundeps    :
    - pycups
    - python-pysmbc
    - python-requests
    - python3-cairo
    - python3-dbus
    - python3-gobject
setup      : |
    %patch -p1 < $pkgfiles/man-fix.patch
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    ./bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
