name       : system-config-printer
version    : 1.5.16
release    : 26
source     :
    - https://github.com/OpenPrinting/system-config-printer/releases/download/v1.5.16/system-config-printer-1.5.16.tar.xz : cbca8409947e4f17877106989aa61ad02bb696c7207c6c353b8815e9e2db37fd
license    : GPL-2.0-only
component  : desktop.core
summary    : Graphical user interface for CUPS administration
description: |
    Graphical user interface for CUPS administration
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(libudev)
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
    - autoconf-archive
    - desktop-file-utils
    - docbook-xml
    - intltool
    - pycups
    - xmlto
rundeps    :
    - cups-filters
    - cups-pk-helper
    - foomatic-db
    - foomatic-db-engine
    - ghostscript
    - gutenprint
    - nss-mdns
    - pycups
    - python3-cairo
    - python3-dbus
    - python-gobject
    - python-pycurl
    - python-pysmbc
    - python-requests
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-man-page-doctype.patch
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0001-dbus-Fix-broken-bindir.patch
    touch ChangeLog README INSTALL
    ./bootstrap
    %configure
build      : |
    %make
install    : |
    %make_install
